version: "3"

services:
  app:
    container_name: "webhook-receiver"
    restart: always
    build: app
    ports:
      - 38080:28080
    networks:
      - nginxproxymanager_default
    volumes:
      - /docker/webhook-tornado/app:/app

networks:
  nginxproxymanager_default:
    external: true