version: "3"

services:
  app:
    container_name: "webhook-receiver"
    restart: always
    build: app
    ports:
      - 38080:8080
    networks:
      - nginxproxymanager_default

networks:
  nginxproxymanager_default:
    external: true